basePath: /
definitions:
  error.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  userm.User:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  userm.UserEmail:
    properties:
      email:
        type: string
    required:
    - email
    type: object
host: localhost:8889
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a mini store application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: authenticate user by providing username and password
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/userm.User'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userm.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: authenticate user
      tags:
      - Authentication
  /api/v1/auth/verify:
    post:
      consumes:
      - application/json
      description: Verify if the user exist by supplying email
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/userm.UserEmail'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userm.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: verify user by email
      tags:
      - Authentication
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
