definitions:
  user.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: add by json account
      parameters:
      - description: Add account
        in: body
        name: account
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.HTTPError'
      summary: Add a account
      tags:
      - accounts
swagger: "2.0"
